# This rule is not used by the project volume-resize-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over storage.maurice.fr.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: volume-resize-operator
    app.kubernetes.io/managed-by: kustomize
  name: volumeresize-admin-role
rules:
- apiGroups:
  - storage.maurice.fr
  resources:
  - volumeresizes
  verbs:
  - '*'
- apiGroups:
  - storage.maurice.fr
  resources:
  - volumeresizes/status
  verbs:
  - get
