apiVersion: storage.maurice.fr/v1alpha1
kind: VolumeResize
metadata:
  labels:
    app.kubernetes.io/name: volume-resize-operator
    app.kubernetes.io/managed-by: kustomize
  name: volumeresize-sample
spec:
  # TODO(user): Add fields here
